// Sinh từ dữ liệu thật, đừng sửa tay.
//
// `NGUON` là cue 41-80 của dự án 5104ff60. `DICH_LECH` là bản dịch THẬT của
// cùng phim đó nhưng lấy từ cue 46-85 — tức là cố ý dịch chuyển đi 5 dòng, để
// có đúng hình dạng của một bản dịch lệch hàng bằng tiếng Việt thật.
//
// KHÔNG phải nhà cung cấp nào trả về thế này. Một phiên bản trước của tệp này
// chú là "bản Gemma trả về" — sai: Gemma dịch đúng hàng, chỗ lệch là do công cụ
// đo cũ bỏ qua cue rỗng khi đọc lại file.
pub const NGUON: &[&str] = &[
    "这次样本得尽量代购，不然回去也查不出什么。",
    "只要还是炭机见了7.62都得急性酮中毒，担心是迁。",
    "那就算并发症，队长笑够了，突击组先行。",
    "回收组间隔50米，人员安全优先上车。",
    "加玛妈。",
    "Unusually large organisms have been reported in coastal regions around.",
    "風異常生物を 捕獲、売買 食用 にしないで ください。",
    "这个头。",
    "真香。",
    ".",
    "上个月的道路影像里，这里还能通车，这片区域氧气浓度已经上升到了26.8%。",
    "进入3号点位。",
    "Okay.",
    "我情况突击左后撤，拉开距离，准备短点射击。",
    ".",
    "我被俘着了，右小腿枪口外直少君处理。",
    "942组64交替就地。",
    "威胁清楚回收组跟进。",
    "Yeah.",
    "林顾问，这里有发现。",
    "清贫弱宠的退壳还没干透，成虫已经离水，数量判断不了。",
    "天损保持警戒，必要时自由开火。天损明白，保持警戒。",
    "高氧能放宽节肢动物的体型上限，但解释不了增速。",
    "也解释不了植被的异常，肚子里还少一个电量。",
    "地面指挥河谷上空大型飞行目标十之以上，请求开火。天隼地面指挥允许开火，保留拖列航线。",
    "都给我滚开。",
    ".",
    "舱事业受阻，近气异常，天损向东脱离。",
    "天损地面指挥收到空域搜索终止。",
    ".",
    "注警走。",
    "这些玩意儿怎么和我看过的电影一样？",
    "11点方向树干右侧疑次目标。",
    "他锁定会动的东西，听口令，左右慢车。",
    "Yeah.",
    "全家了。",
    "我 bring女。",
    "任务结束，我得请半天假，你小子拼了大象。",
    ".",
    "The.",
];
pub const DICH_LECH: &[&str] = &[
    "Đã có báo cáo về các sinh vật lớn bất thường ở các vùng ven biển xung quanh.",
    "Vui lòng không bắt, buôn bán hoặc ăn các sinh vật bất thường này.",
    "Cái đầu này.",
    "Thơm quá.",
    "",
    "Trong ảnh đường tháng trước, ở đây vẫn có thể đi được, nồng độ oxy ở khu vực này đã tăng lên 26,8% rồi.",
    "Vào vị trí số 3.",
    "Okay.",
    "Tôi tình huống đột kích sang trái lùi lại, kéo giãn khoảng cách, chuẩn bị bắn điểm ngắn.",
    "",
    "Tôi bị bắt giữ rồi, chân phải bị bắn, thiếu tá xử lý.",
    "Nhóm 942, 64 luân phiên tại chỗ.",
    "Mục tiêu rõ ràng, nhóm thu hồi theo sau.",
    "Yeah.",
    "Lâm cố vấn, ở đây có phát hiện.",
    "Vỏ trứng của loài yếu ớt bị thương chưa khô, côn trùng trưởng thành đã rời khỏi nước, không thể xác định số lượng.",
    "Thiên tổn giữ cảnh giác, khi cần thiết được tự do bắn. Thiên tổn hiểu rõ, giữ cảnh giác.",
    "Nồng độ oxy cao có thể nới lỏng giới hạn kích thước của động vật giáp xác, nhưng không thể giải thích được tốc độ tăng trưởng.",
    "Cũng không thể giải thích được sự bất thường của thảm thực vật, trong bụng còn thiếu một đơn vị năng lượng.",
    "Bộ chỉ huy trên mặt đất báo cáo có hơn mười mục tiêu bay lớn trên không phận sông suối, yêu cầu được bắn. Bộ chỉ huy mặt đất Thiên Hùng cho phép bắn, giữ nguyên tuyến bay kéo dài.",
    "Cút đi cho tao.",
    "",
    "Công việc trong khoang bị cản trở, khí gần bị bất thường, Thiên tổn di chuyển về phía đông.",
    "Bộ chỉ huy mặt đất Thiên tổn nhận được lệnh chấm dứt tìm kiếm trên không phận.",
    "",
    "Lưu ý cảnh báo, đi thôi.",
    "Cái thứ này sao giống mấy phim tao xem thế nhỉ?",
    "Giờ 11, phía bên phải thân cây nghi là mục tiêu thứ hai.",
    "Nó khóa vào những thứ đang di chuyển, nghe lệnh, rẽ trái phải chậm rãi.",
    "Yeah.",
    "Cả nhà rồi.",
    "Tao mang nữ.",
    "Nhiệm vụ kết thúc, tao phải xin nửa ngày nghỉ, cái thằng nhóc này làm quá.",
    "",
    "The.",
    "Nhóm thu hồi cứ để mắt đến Mã Hiểu, thiếu quân đi theo tôi.",
    "Đúng vậy.",
    "Hoa mẫu đơn không còn mùi nữa.",
    "Mục tiêu xác nhận đã chết, có dân thường bị thương.",
    "Nhóm thu hồi theo dõi tiếp.",
];
